[package]
name = "wasmut"
version = "0.1.0"
edition = "2021"
description = "wasmut: Mutation testing tool for WebAssembly"
license = "MIT"

[features]
default = ["runtime-wasmer"]
runtime-wasmtime = ["wasmtime", "wasmtime-wasi"]
runtime-wasmer = ["wasmer", "wasmer-compiler-cranelift", "wasmer-compiler-singlepass", "wasmer-engine-universal", "wasmer-wasi", "wasmer-middlewares"]

[dependencies]
rayon = "1.5.1"

wasmer = { version = "2.1.1", optional=true}
wasmer-compiler-cranelift = {version = "2.1.1", optional=true}
wasmer-compiler-singlepass = {version = "2.1.1", optional=true}
wasmer-engine-universal = {version = "2.1.1", optional=true}
wasmer-wasi = {version = "2.1.1", optional=true}
wasmer-middlewares = {version = "2.1.1", optional=true}

wasmtime = {version = "0.33.0", optional=true}
wasmtime-wasi = {version = "0.33.0", optional=true}

parity-wasm = { git = "https://github.com/lwagner94/parity-wasm", branch="offsets" }
#parity-wasm = { path = "../parity-wasm" }
anyhow = "1.0.51"
thiserror = "1.0.30"
regex = "1.0.2"
clap = {version = "3.0.0", features=["cargo", "derive"]}
#wabt = "0.10.0"

object = { git = "https://github.com/lwagner94/object", branch="wasm-extended-name-section-quickfix", features = ["read", "wasm"]}
addr2line = "0.17.0"
gimli = "0.26.1"

config = "0.11.0"