[package]
name = "wasmut"
version = "0.1.0"
edition = "2021"
description = "wasmut: Mutation testing tool for WebAssembly"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "2.1.0"
wasmer-compiler-cranelift = "2.1.0"
wasmer-engine-universal = "2.1.0"
wasmer-wasi = "2.1.0"

wasmtime = "0.31.0"
wasmtime-wasi = "0.31.0"

parity-wasm = { git = "https://github.com/lwagner94/parity-wasm", branch="parse_name_fix" }
#parity-wasm = { path = "../parity-wasm" }
anyhow = "1.0.51"
thiserror = "1.0.30"
#wabt = "0.10.0"